### ISSUE TITLE
FRONTEND: Buscar y filtrar empleo

### ISSUE THREAD

**Issue by aliciaperalta** [Meant-Peru/chambeaya-front#126]
**Usuario postulante**

**IMPORTANTE** : Por favor revisar el ticket [#2](https://github.com/Meant-Peru/chambeaya_backend/issues/2) que esta relacionado y ayudará a completar esta tarea.
Pasos:

- [ ] Clic en el logo de chambeaya
- [ ] Ingresar especialidad
- [ ] Ingresar ubicación
- [ ] Seleccionar categoria
- [ ] Clic en Filtrar
- [ ] Se redirige a una pagina con la url /buscar-empleo
- [ ] En esta pagina se mostrará los resultados del filtro.
- [ ] Aparecerá los criterios de entrada que se realizo en la búsqueda y el mismo apartado del filtro.

Video:
https://drive.google.com/file/d/1bCRIALOOzb42AFAXyj5ioun26Fz-0gCO/view?usp=sharing 

![Image](https://user-images.githubusercontent.com/52433321/192012847-09509d7d-9f75-4fc3-a19a-b4e7ca7e2e07.png)

**Notas:**

- [ ] La búsqueda será la siguiente: primero irá el campo categoría donde podrás seleccionar una categoría, según esta opción en el campo de posición se mostrará las posiciones de la categoría, el campo de ubicación se dejara ahí, mas el filtro sólo se hará por el campo de Categoría y Posición.
- [ ] No es necesario ingresar todos los campos (Categoría, Posición, Ubicación) para filtrar/buscar un empleo, puedes ingresar solo un campo y buscará.

**Comment by AlejandraAAO** [comment]
Update:  se estan quitando el envio de token por headers de los servicios: 
getPosition y searchPostJob.

Se subio el cambio a la rama alejandra]/CH-119-empresasypublicaciones con la integracion del servicio getCompany y el filtrado en front del total de post que retorna el servicio getPostAllJob.

**Comment by aliciaperalta** [comment]
@AlejandraAAO cuando filtro una especialidad en la landing principal sale en blanco:



![Image](https://user-images.githubusercontent.com/52433321/197568697-baf3966c-0c5a-4926-a131-caeaef0d06ca.png)

El flujo deberia ser asi:

En la landing principal cuando selecciono una categoria y coloco filtrar me debe llevar a /searchjob con la especialidad que elegi, es decir mostrarme el filtro aplicado



![Image](https://user-images.githubusercontent.com/52433321/197569395-3128eed6-6f36-4d35-8098-5a6c01694581.png)



![Image](https://user-images.githubusercontent.com/52433321/197569538-7ee99610-a274-4632-8174-a23a797c735a.png)

**Comment by edutrul** [comment]
Filtra solamente en el frontend y esto ya lo aprobó el cliente en la DEMO.
