### ISSUE TITLE
Los estilos estan descuadrados en el mobile en administrador

### ISSUE THREAD

**Issue by edutrul** [Meant-Peru/chambeaya-front#158]
![Image](https://user-images.githubusercontent.com/1582129/196573494-20051b20-67d0-4265-88f6-b57901562123.png)

![Image](https://user-images.githubusercontent.com/1582129/196573510-314d4eb4-7fb3-4c59-9fc1-3ad9aeea88f1.png)

![Image](https://user-images.githubusercontent.com/1582129/196573540-3833f97b-4e0f-4871-9185-2a8fca5cde65.png)

Hay que corregir ya que NO se visualiza bien.

**Comment by aliciaperalta** [comment]
@AlejandraAAO el preview del responsive para el admi va bien, lo que falta es en el apartado de empresas como se muestra:



![Image](https://user-images.githubusercontent.com/52433321/198074913-bd57aaf3-e0de-424d-84c2-8da1479c3a9c.png)

En especialidades se muestra asi:



![Image](https://user-images.githubusercontent.com/52433321/198075110-c6a38c22-694b-41da-8e70-d4fdc3a3a4d9.png)

En posiciones de la especialidad se muestra asi:



![Image](https://user-images.githubusercontent.com/52433321/198075288-cb4b82da-9331-4f30-b3b8-160e2291e1c8.png)

Y por lo mismo en editar posiciones



![Image](https://user-images.githubusercontent.com/52433321/198075512-44e39e5b-8204-42ff-975a-b23c77d26fee.png)

Por ultimo en las publicaciones cuando seleccionas una publicación:



![Image](https://user-images.githubusercontent.com/52433321/198076012-65a7a619-44fe-4f58-bf7b-fbd3baf621c4.png)



![Image](https://user-images.githubusercontent.com/52433321/198076080-8b9a9774-0312-4ecb-82d1-ff511833faf5.png)

**Comment by edutrul** [comment]
Ya está listo! validado.
