### ISSUE TITLE
Actualizar detalles de los estilos

### ISSUE THREAD

**Issue by aliciaperalta** [Meant-Peru/chambeaya-front#189]
**Pasos:**

- [ ] Centrar el logo de chambea latam tanto para el escritorio como para mobile, tal como se muestra aqui:

![Image](https://user-images.githubusercontent.com/52433321/198679725-807f8811-25b6-4705-a0d9-ebbb8d1e85da.png)

- [ ] En versión mobile subir un poco más la imagen para que no choque con los botones, tal como se muestra:

![Image](https://user-images.githubusercontent.com/52433321/198679925-72629cf0-b6a8-4fa2-a231-83dec0a2a3bc.png)

- [ ] Dar un espacio entre los botones ya que se encuentra muy junto:

![Image](https://user-images.githubusercontent.com/52433321/198680100-f78bc4c9-c87e-46b3-b663-8182684fc35b.png)

**Comment by AlejandraAAO** [comment]
Listo branch CH-158-admi

**Comment by edutrul** [comment]
Ya se terminó.
