### ISSUE TITLE
Ordenar el apartado de Cartera de negocios alfabéticamente

### ISSUE THREAD

**Issue by aliciaperalta** [Meant-Peru/chambeaya-front#42]
Usuario Ventas

Pasos:

- [ ] Loguearse como role vendedor
- [ ] Cick en el apartado mi perfil
- [ ] Click en el apartado mi cartera
- [ ] A continuación se visualizará las compañías ordenadas alfabéticamente.

![Image](https://user-images.githubusercontent.com/52433321/184949389-d773b494-8d0d-4f31-ae2a-61b185db2c43.png)

**Comment by edutrul** [comment]
Aquí un ejemplo de como ordenar:

```

const students = [
 {
   firstName: "John",
   lastName: "Doe",
   graduationYear: 2022,
   dataUser: {
     businessName: "meant",
   },
 },
 {
   firstName: "Stephen",
   lastName: "Matt",
   graduationYear: 2023,
   dataUser: {
     businessName: "heydru!",
   },
 },
 {
   firstName: "Abigail",
   lastName: "Susu",
   graduationYear: 2022,
   dataUser: {
     businessName: "peid",
   },
 },
 {
   firstName: "Zara",
   lastName: "Kate",
   graduationYear: 2024,
   dataUser: {
     businessName: "silabuz",
   },
 },
 {
   firstName: "Daniel",
   lastName: "Vic",
   graduationYear: 2023,
   dataUser: {
     businessName: "globant",
   },
 }
];

let sortedStudents = students.sort((a, b) => {
 if (a.dataUser.businessName.toLowerCase() < b.dataUser.businessName.toLowerCase()) {
  return -1;
 }
 if (a.dataUser.businessName.toLowerCase() > b.dataUser.businessName.toLowerCase()) {
  return 1;
 }
 return 0;
});
console.log(sortedStudents);
```

**Comment by edutrul** [comment]
@aliciaperalta  https://github.com/Meant-Peru/chambeaya-front/pull/75 ^^ termina este PR. Faltariia comprobar que funcione y sino lo terminas @aliciaperalta

**Comment by edutrul** [comment]
To validate URLs

https://stackoverflow.com/questions/8667070/javascript-regular-expression-to-validate-url
regex
```
/^((https?):\/\/)?([w|W]{3}\.)+[a-zA-Z0-9\-\.]{3,}\.[a-zA-Z]{2,}(\.[a-zA-Z]{2,})?$/
```

```
let validRegex = /^((https?):\/\/)?([w|W]{3}\.)+[a-zA-Z0-9\-\.]{3,}\.[a-zA-Z]{2,}(\.[a-zA-Z]{2,})?$/;

if (!e.target.value.match(validRegex)) {

  alert("NOT VALID url!");
} 
```

**Comment by aliciaperalta** [comment]
Acabo de probar la rama y la funcionalidad de ordenar alfabéticamente la cartera de negocios, en esta imagen se muestra el orden:



![Image](https://user-images.githubusercontent.com/52433321/189165369-b20176d2-6d7a-49fe-9b84-52a88bbbc172.png)

El ticket se realizo desde el frontend ya que así se realiza de una forma más rápida que el backend además de que aún no se pudo desplegar el backend.
