### ISSUE TITLE
Redireccionar el enlace Contacto del menú

### ISSUE THREAD

**Issue by aliciaperalta** [Meant-Peru/chambeaya-front#45]
Pasos:

- [ ] Seleccionar la opción Buscar empleo del menú de la parte superior

![Image](https://user-images.githubusercontent.com/52433321/184993205-416c4acb-3a14-44b0-825a-b69436f0058c.png)

![Image](https://user-images.githubusercontent.com/52433321/184993240-92edcac7-1416-42e8-bab2-265e83f180bc.png)

**Comment by edutrul** [comment]
NO va este enlace. Se hace el push y se cierra el ticket fyi @aliciaperalta
