### ISSUE TITLE
[Cliente] Pasar el nuevo logo de chambea Latam (favico)

### ISSUE THREAD

**Issue by aliciaperalta** [Meant-Peru/chambeaya-front#46]

**Comment by aliciaperalta** [comment]
Pasos:

- [ ] - [ ] Ir a la página https://chambea-ya.com/ 
- [ ] Actualizar el logo que se muestra en todo momento.



![Image](https://user-images.githubusercontent.com/52433321/185645320-252cf699-1979-48bf-90de-88e5ea576503.png)

**Comment by edutrul** [comment]
Está duplicado
