### ISSUE TITLE
Hacer que la web sea responsive en cualquier formato (excepto la landing que ya esta en otro issue)

### ISSUE THREAD

**Issue by aliciaperalta** [Meant-Peru/chambeaya-front#87]
Revisar el estilo responsive en el registro de postulante:

![Image](https://user-images.githubusercontent.com/52433321/198334934-6c9965c8-d87d-4d04-93fc-c678d41f6638.png)

**Comment by edutrul** [comment]
Revisar los estilos en registro de compañia y registro.

![Image](https://user-images.githubusercontent.com/1582129/198176005-1be11e50-aa2e-4386-b974-1bd61136c6c8.png)



Hacer QA

**Comment by edutrul** [comment]
Ya está validado y verificado en la DEMO.
